### ISSUE TITLE
All bounding box values are 0 when using YOLO as output format

### ISSUE THREAD

**Issue by daerty0153** [tzutalin/labelImg#267] opened 2018-03-31 08:47 UTC
Building from source to use YOLO output format. I modified the data/predefined_classes.txt to contain only a single class "person".
VOC seems to be running fine with the following output:
```
<annotation>
	<folder>target</folder>
	<filename>xxx.jpg</filename>
	<path>xxx.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>1080</width>
		<height>1440</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>person</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>204</xmin>
			<ymin>445</ymin>
			<xmax>800</xmax>
			<ymax>1355</ymax>
		</bndbox>
	</object>
	<object>
		<name>person</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>262</xmin>
			<ymin>442</ymin>
			<xmax>859</xmax>
			<ymax>1347</ymax>
		</bndbox>
	</object>
</annotation>
```
But when I try to save the annotation in YOLO format, the generated file is this:

> 0 0.000000 0.000000 0.000000 0.000000
> 0 0.000000 0.000000 0.000000 0.000000

Once I save in the YOLO format and do next and come back, the bounding box also resets to (0,0) in GUI as well.

- **OS: Ubuntu16.04**
- **PyQt version: 4**

**Comment by hkfreenet** [comment] 2018-04-07 13:08
i got the exactly same issue. Please help which step i missed. Thanks!

**Comment by cansik** [comment] 2018-04-08 17:24
Yep, same here on MacOSX, PyQt 5

**Comment by toonvh** [comment] 2018-04-10 11:57
same problem here

**Comment by isVoid** [comment] 2018-04-19 16:49
@daerty0153 I was not able to reproduce your problem on my machine with your data. Found a 1080x1440 image online and pasted your label, switched to yolo and save (you need to move the handle by a bit before you can actually save). This is what I have:

> 0 0.464815 0.625000 0.551852 0.631944
0 0.518519 0.617014 0.551852 0.636806

afaik labelimg has specific way handling folder structures. Can you provide your folder layout? Also detail your steps a bit more if possible.

Michael

**Comment by rosyapril** [comment] 2018-04-23 02:16
I had exactly same problem here. Tested with Python 2 + Qt4, Ubuntu 16.04. All saved values in YOLO format are 0. Even with the windows v1.6.1, all values are 0. 

But it performances alright with VOC data format.

**Comment by isVoid** [comment] 2018-04-23 03:48
@rosyapril Not able to replicate with given DIR structure and class type, I need you to provide more detailed information. Can you provide:

System Environment
Steps to reproduce
Visual Proof (screenshots, videos, text) etc.

Thanks.

**Comment by garry1ng** [comment] 2018-04-25 15:12
@rosyapril I had the same problem with you, and after doing float type casting in YOLO output format as the commit stated below, I found it worked well in both VOC and YOLO output format.
https://github.com/garry1ng/labelImg/commit/7d4ca92d4bf24445640b60a76024b4395f66ed41
I have pulled a request and you can test it.

**Comment by vdalv** [comment] 2018-05-13 18:33
Looks like this bug has been fixed, @tzutalin can we close this issue?

**Closed** 2018-05-22 05:48 UTC
