### ISSUE TITLE
KeyError: <libs.shape.Shape object at 0x00000266308E3710>

### ISSUE THREAD

**Issue by LW-CVer** [tzutalin/labelImg#750] opened 2021-05-18 02:59 UTC
Traceback (most recent call last):
  File "labelImg.py", line 726, in shapeSelectionChanged
    self.shapesToItems[shape].setSelected(True)
KeyError: <libs.shape.Shape object at 0x00000266308E3710>

OS:win10
PyQt version:5

**Comment by pletnes** [comment] 2021-10-15 07:57
Could be a duplicate of #750

**Comment by tzutalin** [comment] 2021-12-27 04:49
Thanks @pletnes who fixed it

**Closed by tzutalin** 2021-12-27 04:49 UTC
Labels: responseRequiredLabel
